In [1]:
import re
import requests
import pandas as pd
from bs4 import BeautifulSoup

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 50)
pd.set_option("display.max_colwidth", 300)
pd.set_option("display.width", 300)

BASE_URL = "https://te4.org/characters-vault"
SITE_URL = "https://te4.org"

MOTS_CLES_INTERDITS = {
    "god",
    "godmode",
    "cheat",
    "experience",
    "tougher escorts",
    "generous",
    "starting prodigy",
    "overpowered",
    "homosuperior",
    "superhuman",
    "expanded shop",
    "no more rare monsters",
    "softcore death",
    "hulk",
    "no prodigy requirement",
    "select your escorts",
    "exponential leveling"
}

PARAMS_BASE = {
    "tag_name": "",
    "tag_level_min": "",
    "tag_level_max": "",
    "tag_winner": "winner",
    "tag_permadeath[]": "66",     # 72=aventure, 66=roguelike
    "tag_difficulty[]": "36",    # 6=normal, 26=nightmare, 36=insane, 227=madness
    "tag_class[]": "23313",          # Berserker
    "tag_campaign[]": "2",        # Age of Ascendancy
}

class_name = "Doombringer"
TALENT_LANGUE_ANGLAISE = "rush"

def get_html(url, params=None, timeout=30):
    reponse = requests.get(url, params=params, timeout=timeout)
    reponse.raise_for_status()
    return reponse.text


def contient_mot_interdit(textes):
    texte = " ".join(textes).lower()

    for mot in MOTS_CLES_INTERDITS:
        if mot.lower() in texte:
            return True, mot

    return False, None


def supprimer_tooltips(bloc):
    for tooltip in bloc.find_all(class_="qtip-tooltip"):
        tooltip.decompose()


def extraire_artefacts_jaunes(html):
    soup = BeautifulSoup(html, "html.parser")

    for titre in soup.find_all("h4"):
        if titre.get_text(strip=True) != "Equipment":
            continue

        tableau = titre.find_next("table")
        if tableau is None:
            return []

        supprimer_tooltips(tableau)

        artefacts = []

        for span in tableau.select('span[style*="#FFD700"]'):
            nom = span.get_text(" ", strip=True)
            if nom:
                artefacts.append(nom)

        return artefacts

    return []


def extraire_page(html):
    soup = BeautifulSoup(html, "html.parser")
    lignes = soup.select("table.sticky-enabled tbody tr")

    donnees = []

    for ligne in lignes:
        cellules = ligne.find_all("td")

        if len(cellules) < 8:
            continue

        lien = cellules[1].find("a")
        url = lien.get("href") if lien else None

        if url and url.startswith("/"):
            url = SITE_URL + url

        donnees.append({
            "user": cellules[0].get_text(strip=True),
            "name": cellules[1].get_text(strip=True),
            "character_url": url,
            "class": cellules[2].get_text(strip=True),
            "difficulty": cellules[3].get_text(strip=True),
            "permadeath": cellules[4].get_text(strip=True),
            "campaign": cellules[5].get_text(strip=True),
            "winner": cellules[6].get_text(strip=True),
            "last_updated": cellules[7].get_text(strip=True),
        })

    return pd.DataFrame(donnees)


def scraper_pages(nb_pages=50):
    tableaux = []

    for page in range(nb_pages):
        html = get_html(BASE_URL, params=PARAMS_BASE | {"page": page})
        df_page = extraire_page(html)

        if df_page.empty:
            print(f"Stop page {page}")
            break

        print(f"Page {page}: {len(df_page)} lignes")
        tableaux.append(df_page)

    return pd.concat(tableaux, ignore_index=True) if tableaux else pd.DataFrame()


def extraire_addons(html):
    soup = BeautifulSoup(html, "html.parser")

    for cellule in soup.find_all("td"):
        if cellule.get_text(strip=True) != "Addons":
            continue

        cellule_addons = cellule.find_next_sibling("td")
        if cellule_addons is None:
            return []

        supprimer_tooltips(cellule_addons)

        addons = []

        for bloc in cellule_addons.find_all("div", class_="addon"):
            nom = bloc.get_text(" ", strip=True)
            if nom:
                addons.append(nom)

        return sorted(set(addons))

    return []


def extraire_prodigies(html):
    soup = BeautifulSoup(html, "html.parser")

    for titre in soup.find_all("h4"):
        if titre.get_text(strip=True) != "Prodigies":
            continue

        tableau = titre.find_next("table", class_="talents")
        if tableau is None:
            return []

        prodigies = []

        for ligne in tableau.find_all("tr"):
            cellule = ligne.find("td")
            if cellule is None:
                continue

            supprimer_tooltips(cellule)

            nom = cellule.get_text(" ", strip=True)
            if nom:
                prodigies.append(nom)

        return prodigies

    return []

def calculer_points_moyens_talents(df_details):
    lignes = []

    for _, ligne in df_details.loc[~df_details["ignore"]].iterrows():
        for talent in ligne["talents"]:
            lignes.append({
                "index_df": ligne["index_df"],
                **talent,
            })

    colonnes = [
        "index_df",
        "type_talent",
        "arbre",
        "multiplicateur_arbre",
        "talent",
        "points",
        "points_max",
    ]

    df_talents = pd.DataFrame(lignes, columns=colonnes)

    if df_talents.empty:
        return df_talents, pd.DataFrame(columns=[
            "type_talent",
            "arbre",
            "talent",
            "points_moyens",
            "points_medians",
            "nb_personnages",
            "points_max",
        ])

    df_moyennes = (
        df_talents
        .groupby(["type_talent", "arbre", "talent"], dropna=False)
        .agg(
            points_moyens=("points", "mean"),
            points_medians=("points", "median"),
            points_mode=("points", lambda x: x.mode().iloc[0] if not x.mode().empty else None),
            nb_personnages=("points", "count"),
            points_max=("points_max", "max"),
        )
        .sort_values(["type_talent", "points_moyens"], ascending=[True, False])
        .reset_index()
    )

    return df_talents, df_moyennes


def analyser_personnage(url):
    html = get_html(url, timeout=10)

    addons = extraire_addons(html)
    ignore, mot = contient_mot_interdit(addons)

    resultat = {
        "url": url,
        "ignore": ignore,
        "mot_interdit": mot,
        "addons": addons,
        "prodigies": [],
        "artefacts_jaunes": [],
        "talents": [],
    }

    if ignore:
        return resultat

    talents = extraire_class_et_generic_talents(html)

    # filtre langue : on garde seulement si "Rush" existe
    noms_talents = {t["talent"].lower() for t in talents}
    if TALENT_LANGUE_ANGLAISE not in noms_talents:
        resultat["ignore"] = True
        resultat["mot_interdit"] = "langue_non_anglaise"
        return resultat

    resultat["talents"] = talents
    resultat["prodigies"] = extraire_prodigies(html)
    resultat["artefacts_jaunes"] = extraire_artefacts_jaunes(html)

    return resultat


def extraire_talents(html, titre_talents):
    soup = BeautifulSoup(html, "html.parser")
    talents = []

    titre = soup.find("h4", string=lambda texte: texte and texte.strip() == titre_talents)
    if titre is None:
        return talents

    tableau = titre.find_next("table", class_="talents")
    if tableau is None:
        return talents

    arbre_courant = None
    multiplicateur_arbre = None

    for ligne in tableau.find_all("tr"):
        cellules = ligne.find_all("td")

        if len(cellules) == 2 and cellules[0].find("strong"):
            arbre_courant = cellules[0].get_text(" ", strip=True)
            multiplicateur_arbre = cellules[1].get_text(strip=True)
            continue

        if len(cellules) < 2:
            continue

        valeur = cellules[-1].get_text(strip=True)
        match = re.search(r"(\d+(?:\.\d+)?)/(\d+(?:\.\d+)?)", valeur)

        if not match:
            continue

        cellule_nom = cellules[0]
        supprimer_tooltips(cellule_nom)

        nom = cellule_nom.get_text(" ", strip=True)

        talents.append({
            "type_talent": titre_talents,
            "arbre": arbre_courant,
            "multiplicateur_arbre": multiplicateur_arbre,
            "talent": nom,
            "points": float(match.group(1)),
            "points_max": float(match.group(2)),
        })

    return talents


def extraire_class_et_generic_talents(html):
    return (
        extraire_talents(html, "Class Talents")
        + extraire_talents(html, "Generic Talents")
    )


def compter_prodigies_et_artefacts(df):
    compteur_prodigies = {}
    compteur_artefacts = {}
    details = []

    for i, url in enumerate(df["character_url"]):
        try:
            resultat = analyser_personnage(url)
            resultat["index_df"] = i
            details.append(resultat)

            if resultat["ignore"]:
                print(f"[IGNORE] #{i} | mot='{resultat['mot_interdit']}'")
                continue

            for prodigy in set(resultat["prodigies"]):
                compteur_prodigies[prodigy] = compteur_prodigies.get(prodigy, 0) + 1

            for artefact in set(resultat["artefacts_jaunes"]):
                compteur_artefacts[artefact] = compteur_artefacts.get(artefact, 0) + 1

            if (i + 1) % 20 == 0:
                print(f"{i + 1} persos traités")

        except Exception as e:
            print(f"Erreur #{i} | {url} | {type(e).__name__}: {e}")

    df_prodigies = (
        pd.DataFrame(compteur_prodigies.items(), columns=["prodigy", "count"])
        .sort_values("count", ascending=False)
        .reset_index(drop=True)
    )

    df_artefacts = (
        pd.DataFrame(compteur_artefacts.items(), columns=["artefact", "count"])
        .sort_values("count", ascending=False)
        .reset_index(drop=True)
    )

    return df_prodigies, df_artefacts, pd.DataFrame(details)


df = scraper_pages(50)

df["race"] = df["name"].str.extract(
    rf"level\s+\d+\s+(\w+)\s+{class_name}",
    expand=False)

compte_par_race = (
    df["race"]
    .value_counts(dropna=False)
    .reset_index(name="count")
)

df_prodigies, df_artefacts, df_details = compter_prodigies_et_artefacts(df)

index_pris_en_compte = df_details.loc[~df_details["ignore"], "index_df"]
df_filtre = df.loc[index_pris_en_compte].reset_index(drop=True)

compte_par_race_filtre = (
    df_filtre["race"]
    .value_counts(dropna=False)
    .reset_index(name="count")
)

df_talents, df_talents_moyens = calculer_points_moyens_talents(df_details)

display(df_filtre.head(15))
display(df_prodigies)
display(df_artefacts.head(100))

df_talents_top = (
    df_talents_moyens
    .loc[df_talents_moyens["nb_personnages"] >= 10]
    .sort_values("points_moyens", ascending=False)
    .reset_index(drop=True)
)

display(df_talents_top)

display(compte_par_race_filtre)

Page 0: 25 lignes
Page 1: 25 lignes
Page 2: 25 lignes
Page 3: 25 lignes
Page 4: 25 lignes
Page 5: 25 lignes
Page 6: 25 lignes
Page 7: 25 lignes
Page 8: 13 lignes
Stop page 9
[IGNORE] #0 | mot='select your escorts'
[IGNORE] #1 | mot='select your escorts'
[IGNORE] #2 | mot='select your escorts'
[IGNORE] #8 | mot='langue_non_anglaise'
[IGNORE] #10 | mot='langue_non_anglaise'
[IGNORE] #11 | mot='langue_non_anglaise'
[IGNORE] #12 | mot='select your escorts'
[IGNORE] #13 | mot='tougher escorts'
[IGNORE] #14 | mot='langue_non_anglaise'
[IGNORE] #15 | mot='langue_non_anglaise'
[IGNORE] #17 | mot='langue_non_anglaise'
[IGNORE] #18 | mot='select your escorts'
[IGNORE] #19 | mot='langue_non_anglaise'
[IGNORE] #24 | mot='select your escorts'
[IGNORE] #26 | mot='select your escorts'
[IGNORE] #27 | mot='langue_non_anglaise'
[IGNORE] #29 | mot='langue_non_anglaise'
[IGNORE] #31 | mot='softcore death'
40 persos traités
[IGNORE] #41 | mot='langue_non_anglaise'
[IGNORE] #45 | mot='select your escorts'
[IGNORE] #52 | mot='select your escorts'
[IGNORE] #57 | mot='langue_non_anglaise'
[IGNORE] #58 | mot='langue_non_anglaise'
60 persos traités
[IGNORE] #61 | mot='select your escorts'
[IGNORE] #63 | mot='langue_non_anglaise'
[IGNORE] #69 | mot='select your escorts'
[IGNORE] #73 | mot='select your escorts'
[IGNORE] #77 | mot='langue_non_anglaise'
[IGNORE] #78 | mot='select your escorts'
80 persos traités
[IGNORE] #84 | mot='select your escorts'
[IGNORE] #86 | mot='select your escorts'
[IGNORE] #91 | mot='langue_non_anglaise'
[IGNORE] #94 | mot='exponential leveling'
[IGNORE] #96 | mot='langue_non_anglaise'
[IGNORE] #98 | mot='langue_non_anglaise'
100 persos traités
[IGNORE] #100 | mot='langue_non_anglaise'
[IGNORE] #101 | mot='select your escorts'
[IGNORE] #102 | mot='langue_non_anglaise'
[IGNORE] #108 | mot='langue_non_anglaise'
[IGNORE] #109 | mot='select your escorts'
[IGNORE] #111 | mot='langue_non_anglaise'
[IGNORE] #114 | mot='select your escorts'
[IGNORE] #118 | mot='select your escorts'
[IGNORE] #119 | mot='langue_non_anglaise'
[IGNORE] #120 | mot='hulk'
[IGNORE] #122 | mot='select your escorts'
[IGNORE] #123 | mot='langue_non_anglaise'
[IGNORE] #125 | mot='select your escorts'
[IGNORE] #131 | mot='langue_non_anglaise'
[IGNORE] #132 | mot='select your escorts'
[IGNORE] #135 | mot='langue_non_anglaise'
[IGNORE] #137 | mot='select your escorts'
140 persos traités
[IGNORE] #146 | mot='select your escorts'
[IGNORE] #152 | mot='select your escorts'
[IGNORE] #155 | mot='select your escorts'
[IGNORE] #158 | mot='select your escorts'
160 persos traités
[IGNORE] #163 | mot='exponential leveling'
[IGNORE] #167 | mot='exponential leveling'
[IGNORE] #168 | mot='select your escorts'
[IGNORE] #175 | mot='select your escorts'
[IGNORE] #176 | mot='select your escorts'
[IGNORE] #177 | mot='exponential leveling'
180 persos traités
[IGNORE] #180 | mot='select your escorts'
[IGNORE] #184 | mot='select your escorts'
[IGNORE] #188 | mot='select your escorts'
[IGNORE] #192 | mot='langue_non_anglaise'
[IGNORE] #197 | mot='select your escorts'
[IGNORE] #198 | mot='select your escorts'
200 persos traités
[IGNORE] #200 | mot='select your escorts'
[IGNORE] #201 | mot='select your escorts'
[IGNORE] #203 | mot='select your escorts'
[IGNORE] #204 | mot='select your escorts'
[IGNORE] #206 | mot='exponential leveling'

                user                                                      name                                                                character_url        class difficulty permadeath  campaign winner           last_updated      race
0              tsvit                       Mebo the level 50 Dwarf Doombringer  https://te4.org/characters/399137/tome/9e208d8a-ec81-424e-b4b3-06bf021dbe54  doombringer     insane  roguelike  maj'eyal    yes     2 weeks 2 days ago     Dwarf
1           Siewiorr                       Doul the level 50 Ghoul Doombringer  https://te4.org/characters/285927/tome/be257945-12dd-4eb0-8c27-a5f78f8577ad  doombringer     insane  roguelike  maj'eyal    yes     2 weeks 2 days ago     Ghoul
2              prodo               Dr.Insano the level 50 Skeleton Doombringer  https://te4.org/characters/398635/tome/8f09200c-68d0-4ce6-ba95-f347c28acfc2  doombringer     insane  roguelike  maj'eyal    yes     3 weeks 6 days ago  Skeleton
3            wtsai89        little destroyer the level 50 Halfling Doombringer  https://te4.org/characters/128024/tome/c0bcec53-12e0-4c02-8853-3c5a6332f25a  doombringer     insane  roguelike  maj'eyal    yes     3 weeks 6 days ago  Halfling
4         KannKarate                    Ironclad the level 50 Ogre Doombringer  https://te4.org/characters/218167/tome/9737a6bd-5ac9-4e7c-aeb4-e77e6f67cd8d  doombringer     insane  roguelike  maj'eyal    yes   5 weeks 11 hours ago      Ogre
5          Gorbleezi                    Riala the level 50 Shalore Doombringer  https://te4.org/characters/224193/tome/74339c16-ec86-4e3c-ae58-0e68518e1f99  doombringer     insane  roguelike  maj'eyal    yes     9 weeks 5 days ago   Shalore
6           malirain                       Kabas the level 50 Ogre Doombringer  https://te4.org/characters/255494/tome/bcc6f123-ba04-478a-aa30-b074cff71f33  doombringer     insane  roguelike  maj'eyal    yes    19 weeks 5 days ago      Ogre
7           Siewiorr          Skelly of doom the level 50 Skeleton Doombringer  https://te4.org/characters/285927/tome/7625977d-3761-4ca9-a8bf-e5019d9492fe  doombringer     insane  roguelike  maj'eyal    yes     21 weeks 1 day ago  Skeleton
8            Daricus               Flynn Taggart the level 50 Ogre Doombringer  https://te4.org/characters/266101/tome/08a8ada8-191f-49a6-bebf-a96288c368b6  doombringer     insane  roguelike  maj'eyal    yes    23 weeks 5 days ago      Ogre
9          firmament                      Euijoo the level 50 Ogre Doombringer  https://te4.org/characters/261241/tome/07e16a73-5468-4862-b220-d9fcb89e414e  doombringer     insane  roguelike  maj'eyal    yes    24 weeks 4 days ago      Ogre
10       knifebutton             SkelBringer the level 50 Skeleton Doombringer  https://te4.org/characters/212909/tome/f564302c-0df0-4d7a-817b-ae488f11314d  doombringer     insane  roguelike  maj'eyal    yes    25 weeks 4 days ago  Skeleton
11    VerhomNaZvezde              ShalavaDoom the level 50 Shalore Doombringer  https://te4.org/characters/286580/tome/171c92f2-602e-4242-8cb8-fab456a0e0b6  doombringer     insane  roguelike  maj'eyal    yes  28 weeks 13 hours ago   Shalore
12  solanumtuberosum                 Naramyr the level 50 Halfling Doombringer  https://te4.org/characters/134035/tome/8189a7ef-4890-4525-81e5-60692a8b752d  doombringer     insane  roguelike  maj'eyal    yes    37 weeks 6 days ago  Halfling
13          Megumin!  kamidere gyaru balor gf the level 50 Doomelf Doombringer  https://te4.org/characters/305560/tome/e0468f79-8572-4def-950f-3d0d780f23a8  doombringer     insane  roguelike  maj'eyal    yes     40 weeks 1 day ago   Doomelf
14             Azeal                    Cyrintha the level 50 Drem Doombringer  https://te4.org/characters/211726/tome/cb17b894-06b3-4471-9ec7-ca0b8864fcf5  doombringer     insane  roguelike  maj'eyal    yes     41 weeks 1 day ago      Drem

                       prodigy  count
0              Flexible Combat     70
1                 Arcane Might     59
2                Ethereal Form     54
3       I Can Carry The World!     45
4                        Adept     12
5                    Cauterize     12
6              Corrupted Shell      7
7      Pain Enhancement System      5
8             Irresistible Sun      4
9           Spine of the World      3
10                  Giant Leap      3
11       Legacy of the Naloren      3
12           Worldly Knowledge      2
13         Master of Disasters      2
14              Meteoric Crash      2
15               Draconic Will      2
16         Revisionist History      1
17           Aether Permeation      1
18           Windtouched Speed      1
19                Massive Blow      1
20                 Swift Hands      1
21                   Windblade      1
22         Tricks of the Trade      1
23                Fungal Blood      1
24          Never Stop Running      1
25                  Superpower      1
26                Roll With It      1
27           Fast As Lightning      1
28                Endless Woes      1
29            Eye of the Tiger      1
30            Unbreakable Will      1
31                 Bloodspring      1
32  Subcutaneous Metallisation      1
33             Elemental Surge      1
34     You Shall Be My Weapon!      1
35          Rak'Shor's Cunning      1
36           Armour of Shadows      1
37                 Steamroller      1
38               Draconic Body      1

                                                         artefact  count
0                           Dakhtun's Gauntlets (0 def, 6 armour)     68
1                          Unbreakable Greaves (8 def, 20 armour)     38
2                             The Black Plate (25 def, 35 armour)     35
3                                     Limmir's Amulet of the Moon     30
4                                                   Wheel of Fate     26
5                                   Dethblyd (182% power, 18 apr)     22
6                                 Dethblyd (70-112 power, 18 apr)     20
7                          Boots of the Hunter (2 def, 12 armour)     19
8                             Will of Ul'Gruth (0 def, 15 armour)     18
9                                    Aetherwalk (6 def, 0 armour)     17
10                                                    Bloodcaller     12
11                                                            Vox     11
12                Plate of the Blackened Mind (15 def, 40 armour)     10
13                                               Ring of the Dead     10
14                   Blade of Distorted Time (150% power, 40 apr)      8
15                                         Girdle of Preservation      8
16                                                Choker of Dread      7
17                      Mandible of Ungolmor (150% power, 12 apr)      7
18                                         Ring of the War Master      6
19                                               Dúathedlen Heart      6
20                            Eastern Wood Hat (15 def, 0 armour)      6
21                        Fist of the Destroyer (8 def, 0 armour)      5
22                                                 The Black Core      5
23                 Helm of the Dwarven Emperors (0 def, 6 armour)      4
24                                                  Planar Beacon      4
25                                             Glory of the Pride      4
26                             Blighted Maul (204% power, 22 apr)      4
27                                       Bikini (0 def, 0 armour)      3
28                                                Unflinching Eye      3
29                                                  Fanged Collar      3
30                                    Radiance (15 def, 0 armour)      3
31                            Eye of the Forest (8 def, 0 armour)      3
32                                             Eternity's Counter      3
33                           Blighted Maul (96-144 power, 22 apr)      3
34                  Pick of Dwarven Emperors (dig speed 12 turns)      3
35                          Chromatic Harness (10 def, 14 armour)      3
36                                                   Tree of Life      3
37                            The Black Maul (182% power, 15 apr)      3
38                               Frozen Shroud (12 def, 0 armour)      3
39                                                   The Far-Hand      2
40                         Void Quiver (0/0, 156% power, 120 apr)      2
41                                    Masochism (0 def, 0 armour)      2
42            Warmaster Gnarg's Murderblade (60-96 power, 19 apr)      2
43                          The Black Maul (70-105 power, 15 apr)      2
44                                    Tarrasca (0 def, 50 armour)      2
45                                     Zemekkys' Broken Hourglass      2
46                       Dragon-helm of Kroltar (5 def, 9 armour)      2
47                      Scale Mail of Kroltar (20 def, 18 armour)      2
48                                              Emblem of Evasion      2
49                      Nimbus of Enlightenment (7 def, 0 armour)      2
50                              Wanderer's Rest (4 def, 0 armour)      2
51                The Titan's Quiver (18/18, 62-87 power, 20 apr)      2
52                            The Black Plate (25 def, 45 armour)      2
53                          Steam Powered Helm (3 def, 12 armour)      2
54                  Quiver of the Sun (25/25, 142% power, 15 apr)      2
55                                                   Cut Drem Arm      2
56                                      Mercy (143% power, 9 apr)      2
57                       Crown of the Elements (0 def, 10 armour)      2
58                              Quasit's Skull (0 def, 12 armour)      2
59                                               Wintertide Phial      2
60                     Legacy of the Naloren (194% power, 20 apr)      2
61                        Khulmanar's Wrath (70-105 power, 8 apr)      2
62                         Steel Helm of Garkul (0 def, 6 armour)      2
63                                 Eden's Guile (2 def, 1 armour)      2
64                                      Mankini (0 def, 0 armour)      1
65  Seeds of the Black Tree (115% power, 27 apr, darkness damage)      1
66                                                 Neira's Memory      1
67                    Poltergeist's Dethblyd (182% power, 18 apr)      1
68                Stone Gauntlets of Harkor'Zun (0 def, 7 armour)      1
69                           Tirakai's Maul (68-88 power, 15 apr)      1
70                         Galen's Flowing Robe (0 def, 0 armour)      1
71                 Fists of the Desert Scorpion (8 def, 4 armour)      1
72                  Blade of Distorted Time (40-56 power, 40 apr)      1
73                     Mandible of Ungolmor (40-52 power, 12 apr)      1
74                            Monolith Armour (40 def, 50 armour)      1
75                                                     Umbraphage      1
76    Crystalline Yew magestaff (129% power, 4 apr, fire element)      1
77                                                       Void Orb      1
78                 Crystalline Elven-silk robe  (3 def, 5 armour)      1
79                        Helm of the Dominated (0 def, 9 armour)      1
80                    Storm Bringer's Gauntlets (0 def, 5 armour)      1
81                        Void Quiver (0/0, 45-63 power, 120 apr)      1
82                             Threads of Fate (10 def, 0 armour)      1
83                                   Worm Nest (0 def, 20 armour)      1
84                                    Writhing Ring of the Hunter      1
85                   Malslek the Accursed's Hat (2 def, 0 armour)      1
86                                   Masochism (0 def, 10 armour)      1
87                                Molten Skin (15 def, 12 armour)      1
88             Arkul's Siege Arrows (14/14, 68-95 power, 100 apr)      1
89                            Dethblyd (227 - 364 damage, 38 apr)      1
90                          Guise of the Hated (14 def, 0 armour)      1
91                 Quiver of the Sun (25/25, 34-48 power, 15 apr)      1
92                             Skeletal Claw (55-61 power, 8 apr)      1
93                         Star Shot (20/20, 32-38 power, 15 apr)      1
94                           Whip of Urh'Rok (55-60 power, 0 apr)      1
95                            Destala's Scales (10 def, 0 armour)      1
96                                    Masochism (0 def, 5 armour)      1
97                                  Dethblyd (182% power, 38 apr)      1
98                                   Butcher (159% power, 12 apr)      1
99                                            Bizzare Contraption      1

         type_talent                          arbre                     talent  points_moyens  points_medians  points_mode  nb_personnages  points_max
0      Class Talents             Corruption / Wrath                  Destroyer       4.869565             5.0          5.0             138         5.0
1      Class Talents         Corruption / Brutality           Draining Assault       4.571429             5.0          5.0             140         5.0
2      Class Talents           Corruption / Torture                  Abduction       4.371429             5.0          5.0             140         5.0
3      Class Talents         Corruption / Brutality            Reckless Strike       4.285714             5.0          5.0             140         5.0
4      Class Talents             Corruption / Wrath         Obliterating Smash       4.115942             5.0          5.0             138         5.0
5      Class Talents  Technique / Combat techniques             Blinding Speed       4.050000             5.0          5.0             140         5.0
6      Class Talents       Corruption / Shadowflame           Flame of Urh'Rok       4.035714             5.0          5.0             140         5.0
7      Class Talents         Corruption / Brutality                Fiery Grasp       3.307143             4.0          4.0             140         5.0
8      Class Talents          Corruption / Fearfire           Cauterize Spirit       3.148760             3.0          3.0             121         5.0
9      Class Talents           Corruption / Torture         Incinerating Blows       2.985714             4.0          1.0             140         5.0
10     Class Talents  Technique / Combat techniques            Precise Strikes       2.885714             3.5          5.0             140         5.0
11     Class Talents  Technique / Combat techniques             Perfect Strike       2.821429             3.0          1.0             140         5.0
12     Class Talents           Corruption / Torture          Eternal Suffering       2.757143             4.0          5.0             140         5.0
13     Class Talents         Corruption / Brutality             Share the Pain       2.742857             3.0          5.0             140         5.0
14     Class Talents          Corruption / Fearfire            Fearscape Shift       2.561983             2.0          1.0             121         5.0
15     Class Talents             Corruption / Wrath          Detonating Charge       2.275362             2.0          1.0             138         5.0
16     Class Talents     Corruption / Heart of Fire            Blazing Rebirth       2.228571             3.0          3.0             140         5.0
17     Class Talents  Technique / Combat techniques                       Rush       2.078571             1.0          1.0             140         5.0
18     Class Talents             Corruption / Wrath            Voracious Blade       1.971014             1.0          1.0             138         5.0
19     Class Talents           Corruption / Torture              Fiery Torment       1.771429             1.0          1.0             140         5.0
20     Class Talents     Corruption / Heart of Fire          Burning Sacrifice       1.328571             1.0          1.0             140         5.0
21     Class Talents     Corruption / Heart of Fire                Fiery Aegis       1.280576             1.0          1.0             139         5.0
22     Class Talents       Corruption / Shadowflame                 Wraithform       1.207143             1.0          1.0             140         5.0
23     Class Talents     Corruption / Heart of Fire           Devouring Flames       1.121429             1.0          1.0             140         5.0
24     Class Talents     Corruption / Heart of Fire              Inferno Nexus       1.000000             1.0          1.0               1         5.0
25     Class Talents       Corruption / Shadowflame                   Darkfire       0.950000             1.0          1.0             140         5.0
26     Class Talents       Corruption / Shadowflame                  Fearscape       0.814286             1.0          1.0             140         5.0
27     Class Talents          Corruption / Fearfire            Infernal Breath       0.487603             0.0          0.0             121         5.0
28     Class Talents     Technique / Combat veteran               Spell Shield       0.378571             0.0          0.0             140         5.0
29     Class Talents     Technique / Combat veteran             Quick Recovery       0.364286             0.0          0.0             140         5.0
30     Class Talents     Technique / Combat veteran            Fast Metabolism       0.307143             0.0          0.0             140         5.0
31     Class Talents          Corruption / Fearfire             Maw of Urh'rok       0.225000             0.0          0.0             120         5.0
32     Class Talents     Technique / Combat veteran            Unending Frenzy       0.135714             0.0          0.0             140         5.0
33     Class Talents          Corruption / Fearfire             Fearscape Aura       0.000000             0.0          0.0               1         5.0
34   Generic Talents      Chronomancy / Chronomancy                Contingency       5.000000             5.0          5.0               1         5.0
35   Generic Talents      Chronomancy / Chronomancy                  Foresight       5.000000             5.0          5.0               1         5.0
36   Generic Talents      Chronomancy / Chronomancy               Precognition       5.000000             5.0          5.0               1         5.0
37   Generic Talents            Cunning / Scoundrel           Nimble Movements       5.000000             5.0          5.0               1         5.0
38   Generic Talents   Psionic / Augmented mobility           Quick as Thought       5.000000             5.0          5.0               1         5.0
39   Generic Talents          Spell / Stone alchemy                 Imbue Item       5.000000             5.0          5.0               2         5.0
40   Generic Talents              Undead / Skeleton                Re-assemble       5.000000             5.0          5.0              12         5.0
41   Generic Talents             Wild-gift / Fungus                Wild Growth       5.000000             5.0          5.0               1         5.0
42   Generic Talents                 Race / Shalore                   Timeless       4.916667             5.0          5.0              12         5.0
43   Generic Talents                    Race / Ogre        Grisly Constitution       4.885714             5.0          5.0              35         5.0
44   Generic Talents    Technique / Combat training            Weapons Mastery       4.728571             5.0          5.0             140         5.0
45   Generic Talents  Corruption / Demonic strength             Abyssal Shield       4.714286             5.0          5.0             140         5.0
46   Generic Talents                    Race / Yeek                  Quickened       4.400000             5.0          5.0               5         5.0
47   Generic Talents  Corruption / Demonic strength              Demonic Blood       4.192857             5.0          5.0             140         5.0
48   Generic Talents    Technique / Combat training                 Thick Skin       4.092857             5.0          5.0             140         5.0
49   Generic Talents          Wild-gift / Antimagic           Antimagic Shield       4.000000             4.0          4.0               1         5.0
50   Generic Talents          Wild-gift / Antimagic                    Resolve       4.000000             4.0          4.0               1         5.0
51   Generic Talents            Wild-gift / Harmony          Elemental Harmony       4.000000             5.0          5.0               4         5.0
52   Generic Talents       Technique / Conditioning        Unflinching Resolve       3.777778             4.0          4.0               9         5.0
53   Generic Talents              Celestial / Light                 Providence       3.750000             4.0          5.0               4         5.0
54   Generic Talents                 Race / Doomelf   Resilience of the Doomed       3.666667             5.0          5.0               6         5.0
55   Generic Talents    Technique / Combat training            Armour Training       3.666667             5.0          5.0               9         5.0
56   Generic Talents                 Undead / Ghoul              Ghoulish Leap       3.666667             4.0          5.0               6         5.0
57   Generic Talents    Technique / Combat training            Combat Accuracy       3.600000             4.0          5.0             140         5.0
58   Generic Talents            Cunning / Scoundrel               Misdirection       3.500000             4.0          5.0               6         5.0
59   Generic Talents         Corruption / Vile life               Blood Splash       3.428571             5.0          5.0               7         5.0
60   Generic Talents                 Race / Shalore      Magic of the Eternals       3.416667             4.0          5.0              12         5.0
61   Generic Talents                   Race / Dwarf             Power is Money       3.400000             5.0          5.0              10         5.0
62   Generic Talents                  Race / Higher           Highborn's Bloom       3.375000             4.5          5.0               8         5.0
63   Generic Talents        Corruption / Oppression           Horrifying Blows       3.250000             4.0          5.0             140         5.0
64   Generic Talents              Undead / Skeleton                Bone Armour       3.250000             3.0          3.0              12         5.0
65   Generic Talents  Corruption / Demonic strength                  Dismember       3.214286             4.0          5.0             140         5.0
66   Generic Talents                  Race / Higher            Born into Magic       3.125000             3.0          5.0               8         5.0
67   Generic Talents            Cunning / Scoundrel         Lacerating Strikes       3.000000             3.0          1.0               6         5.0
68   Generic Talents                    Race / Ogre                 Writ Large       3.000000             2.0          2.0              35         5.0
69   Generic Talents                Race / Halfling             Duck and Dodge       2.875000             2.0          1.0              16         5.0
70   Generic Talents            Cunning / Scoundrel     Scoundrel's Strategies       2.833333             2.5          1.0               6         5.0
71   Generic Talents    Technique / Combat training      Heavy Armour Training       2.832061             3.0          1.0             131         5.0
72   Generic Talents       Technique / Conditioning                   Vitality       2.666667             2.0          1.0               9         5.0
73   Generic Talents                  Race / Higher        Overseer of Nations       2.625000             2.0          1.0               8         5.0
74   Generic Talents                    Race / Yeek                      Unity       2.600000             2.0          1.0               5         5.0
75   Generic Talents       Technique / Conditioning          Daunting Presence       2.555556             3.0          0.0               9         5.0
76   Generic Talents              Celestial / Light              Healing Light       2.500000             2.0          1.0               4         5.0
77   Generic Talents                 Race / Doomelf                   Pitiless       2.500000             2.0          1.0               6         5.0
78   Generic Talents                Race / Parasite             Ultra Instinct       2.500000             2.5          0.0               2         5.0
79   Generic Talents            Steamtech / Physics                      Smith       2.411765             2.0          2.0              17         5.0
80   Generic Talents             Cunning / Survival             Device Mastery       2.401575             1.0          5.0             127         5.0
81   Generic Talents            Cunning / Scoundrel                     Fumble       2.400000             2.0          2.0               5         5.0
82   Generic Talents                 Race / Doomelf   Corruption of the Doomed       2.333333             1.0          1.0               6         5.0
83   Generic Talents             Celestial / Chants              Chant Acolyte       2.285714             1.0          1.0              14         5.0
84   Generic Talents              Celestial / Light             Bathe in Light       2.250000             2.0          1.0               4         5.0
85   Generic Talents            Wild-gift / Harmony             Waters of Life       2.250000             1.5          1.0               4         5.0
86   Generic Talents                    Race / Drem      From Below It Devours       2.222222             1.0          1.0               9         5.0
87   Generic Talents          Steamtech / Chemistry               Therapeutics       2.176471             1.0          1.0              17         5.0
88   Generic Talents              Undead / Skeleton                   Skeleton       2.083333             1.0          1.0              12         5.0
89   Generic Talents              Celestial / Light                    Barrier       2.000000             1.0          1.0               4         5.0
90   Generic Talents                 Race / Doomelf        Haste of the Doomed       2.000000             1.0          1.0               6         5.0
91   Generic Talents                 Race / Thalore       Guardian of the Wood       2.000000             2.0          1.0               2         5.0
92   Generic Talents              Undead / Skeleton            Resilient Bones       2.000000             1.0          1.0              12         5.0
93   Generic Talents            Wild-gift / Harmony              Healing Nexus       2.000000             1.5          0.0               4         5.0
94   Generic Talents                    Race / Drem                   Faceless       1.888889             1.0          1.0               9         5.0
95   Generic Talents  Corruption / Demonic strength             Surge of Power       1.864286             1.0          1.0             140         5.0
96   Generic Talents        Corruption / Oppression                 Hope Wanes       1.821429             0.0          0.0             140         5.0
97   Generic Talents             Celestial / Chants                Chant Adept       1.714286             1.0          1.0              14         5.0
98   Generic Talents             Cunning / Survival              Charm Mastery       1.666667             0.0          0.0               9         5.0
99   Generic Talents            Steamtech / Physics                 Mechanical       1.647059             2.0          2.0              17         5.0
100  Generic Talents                Race / Halfling              Militant Mind       1.625000             1.0          1.0              16         5.0
101  Generic Talents                   Race / Dwarf                  Stoneskin       1.600000             1.0          1.0              10         5.0
102  Generic Talents                Race / Halfling                Indomitable       1.562500             1.0          1.0              16         5.0
103  Generic Talents          Spell / Stone alchemy                Stone Touch       1.500000             1.5          0.0               2         5.0
104  Generic Talents            Wild-gift / Harmony            One with Nature       1.500000             0.5          0.0               4         5.0
105  Generic Talents             Cunning / Survival             Piercing Sight       1.444444             1.0          1.0               9         5.0
106  Generic Talents                    Race / Drem                     Frenzy       1.444444             1.0          1.0               9         5.0
107  Generic Talents                    Race / Ogre        Scar-Scripted Flesh       1.342857             1.0          1.0              35         5.0
108  Generic Talents                 Race / Shalore      Grace of the Eternals       1.333333             1.0          1.0              12         5.0
109  Generic Talents             Celestial / Chants           Chant Illuminate       1.285714             1.0          1.0              14         5.0
110  Generic Talents                Race / Halfling    Luck of the Little Folk       1.250000             1.0          1.0              16         5.0
111  Generic Talents    Technique / Combat training      Light Armour Training       1.213740             0.0          0.0             131         5.0
112  Generic Talents            Steamtech / Physics                Electricity       1.176471             1.0          1.0              17         5.0
113  Generic Talents         Corruption / Vile life            Vile Transplant       1.142857             0.0          0.0               7         5.0
114  Generic Talents           Spell / Staff combat              Channel Staff       1.142857             1.0          0.0               7         5.0
115  Generic Talents           Spell / Staff combat              Staff Mastery       1.142857             1.0          0.0               7         5.0
116  Generic Talents                    Race / Ogre                Ogric Wrath       1.114286             1.0          1.0              35         5.0
117  Generic Talents                    Race / Drem                  Spikeskin       1.111111             1.0          1.0               9         5.0
118  Generic Talents      Chronomancy / Chronomancy            See the Threads       1.000000             1.0          1.0               1         5.0
119  Generic Talents         Corruption / Vile life          Elemental Discord       1.000000             1.0          0.0               7         5.0
120  Generic Talents   Psionic / Augmented mobility                      Skate       1.000000             1.0          1.0               1         5.0
121  Generic Talents                   Race / Dwarf  Resilience of the Dwarves       1.000000             1.0          1.0              10         5.0
122  Generic Talents                  Race / Higher       Gift of the Highborn       1.000000             1.0          1.0               1         5.0
123  Generic Talents                  Race / Higher      Wrath of the Highborn       1.000000             1.0          1.0               7         5.0
124  Generic Talents                    Race / Krog        Drake-Infused Blood       1.000000             1.0          1.0               1         5.0
125  Generic Talents                    Race / Krog                  Fuel Pain       1.000000             1.0          1.0               1         5.0
126  Generic Talents                    Race / Krog                    Warborn       1.000000             1.0          1.0               1         5.0
127  Generic Talents                    Race / Krog         Wrath of the Wilds       1.000000             1.0          1.0               1         5.0
128  Generic Talents                Race / Parasite                Take a Bite       1.000000             1.0          1.0               2         5.0
129  Generic Talents                 Race / Shalore    Secrets of the Eternals       1.000000             1.0          1.0              12         5.0
130  Generic Talents                 Race / Thalore          Gift of the Woods       1.000000             1.0          1.0               2         5.0

        race  count
0       Ogre     35
1     Cornac     17
2   Halfling     16
3    Shalore     12
4   Skeleton     12
5      Dwarf     11
6       Drem      9
7     Higher      8
8      Ghoul      6
9    Doomelf      6
10      Yeek      5
11   Thalore      2
12      Krog      1

        type_talent                          arbre                     talent  points_moyens  points_medians  points_mode  nb_personnages  points_max
0   Generic Talents              Undead / Skeleton                Re-assemble       5.000000             5.0          5.0              12         5.0
1   Generic Talents                 Race / Shalore                   Timeless       4.916667             5.0          5.0              12         5.0
2   Generic Talents                    Race / Ogre        Grisly Constitution       4.885714             5.0          5.0              35         5.0
3     Class Talents             Corruption / Wrath                  Destroyer       4.869565             5.0          5.0             138         5.0
4   Generic Talents    Technique / Combat training            Weapons Mastery       4.728571             5.0          5.0             140         5.0
5   Generic Talents  Corruption / Demonic strength             Abyssal Shield       4.714286             5.0          5.0             140         5.0
6     Class Talents         Corruption / Brutality           Draining Assault       4.571429             5.0          5.0             140         5.0
7     Class Talents           Corruption / Torture                  Abduction       4.371429             5.0          5.0             140         5.0
8     Class Talents         Corruption / Brutality            Reckless Strike       4.285714             5.0          5.0             140         5.0
9   Generic Talents  Corruption / Demonic strength              Demonic Blood       4.192857             5.0          5.0             140         5.0
10    Class Talents             Corruption / Wrath         Obliterating Smash       4.115942             5.0          5.0             138         5.0
11  Generic Talents    Technique / Combat training                 Thick Skin       4.092857             5.0          5.0             140         5.0
12    Class Talents  Technique / Combat techniques             Blinding Speed       4.050000             5.0          5.0             140         5.0
13    Class Talents       Corruption / Shadowflame           Flame of Urh'Rok       4.035714             5.0          5.0             140         5.0
14  Generic Talents    Technique / Combat training            Combat Accuracy       3.600000             4.0          5.0             140         5.0
15  Generic Talents                 Race / Shalore      Magic of the Eternals       3.416667             4.0          5.0              12         5.0
16  Generic Talents                   Race / Dwarf             Power is Money       3.400000             5.0          5.0              10         5.0
17    Class Talents         Corruption / Brutality                Fiery Grasp       3.307143             4.0          4.0             140         5.0
18  Generic Talents        Corruption / Oppression           Horrifying Blows       3.250000             4.0          5.0             140         5.0
19  Generic Talents              Undead / Skeleton                Bone Armour       3.250000             3.0          3.0              12         5.0
20  Generic Talents  Corruption / Demonic strength                  Dismember       3.214286             4.0          5.0             140         5.0
21    Class Talents          Corruption / Fearfire           Cauterize Spirit       3.148760             3.0          3.0             121         5.0
22  Generic Talents                    Race / Ogre                 Writ Large       3.000000             2.0          2.0              35         5.0
23    Class Talents           Corruption / Torture         Incinerating Blows       2.985714             4.0          1.0             140         5.0
24    Class Talents  Technique / Combat techniques            Precise Strikes       2.885714             3.5          5.0             140         5.0
25  Generic Talents                Race / Halfling             Duck and Dodge       2.875000             2.0          1.0              16         5.0
26  Generic Talents    Technique / Combat training      Heavy Armour Training       2.832061             3.0          1.0             131         5.0
27    Class Talents  Technique / Combat techniques             Perfect Strike       2.821429             3.0          1.0             140         5.0
28    Class Talents           Corruption / Torture          Eternal Suffering       2.757143             4.0          5.0             140         5.0
29    Class Talents         Corruption / Brutality             Share the Pain       2.742857             3.0          5.0             140         5.0
30    Class Talents          Corruption / Fearfire            Fearscape Shift       2.561983             2.0          1.0             121         5.0
31  Generic Talents            Steamtech / Physics                      Smith       2.411765             2.0          2.0              17         5.0
32  Generic Talents             Cunning / Survival             Device Mastery       2.401575             1.0          5.0             127         5.0
33  Generic Talents             Celestial / Chants              Chant Acolyte       2.285714             1.0          1.0              14         5.0
34    Class Talents             Corruption / Wrath          Detonating Charge       2.275362             2.0          1.0             138         5.0
35    Class Talents     Corruption / Heart of Fire            Blazing Rebirth       2.228571             3.0          3.0             140         5.0
36  Generic Talents          Steamtech / Chemistry               Therapeutics       2.176471             1.0          1.0              17         5.0
37  Generic Talents              Undead / Skeleton                   Skeleton       2.083333             1.0          1.0              12         5.0
38    Class Talents  Technique / Combat techniques                       Rush       2.078571             1.0          1.0             140         5.0
39  Generic Talents              Undead / Skeleton            Resilient Bones       2.000000             1.0          1.0              12         5.0
40    Class Talents             Corruption / Wrath            Voracious Blade       1.971014             1.0          1.0             138         5.0
41  Generic Talents  Corruption / Demonic strength             Surge of Power       1.864286             1.0          1.0             140         5.0
42  Generic Talents        Corruption / Oppression                 Hope Wanes       1.821429             0.0          0.0             140         5.0
43    Class Talents           Corruption / Torture              Fiery Torment       1.771429             1.0          1.0             140         5.0
44  Generic Talents             Celestial / Chants                Chant Adept       1.714286             1.0          1.0              14         5.0
45  Generic Talents            Steamtech / Physics                 Mechanical       1.647059             2.0          2.0              17         5.0
46  Generic Talents                Race / Halfling              Militant Mind       1.625000             1.0          1.0              16         5.0
47  Generic Talents                   Race / Dwarf                  Stoneskin       1.600000             1.0          1.0              10         5.0
48  Generic Talents                Race / Halfling                Indomitable       1.562500             1.0          1.0              16         5.0
49  Generic Talents                    Race / Ogre        Scar-Scripted Flesh       1.342857             1.0          1.0              35         5.0
50  Generic Talents                 Race / Shalore      Grace of the Eternals       1.333333             1.0          1.0              12         5.0
51    Class Talents     Corruption / Heart of Fire          Burning Sacrifice       1.328571             1.0          1.0             140         5.0
52  Generic Talents             Celestial / Chants           Chant Illuminate       1.285714             1.0          1.0              14         5.0
53    Class Talents     Corruption / Heart of Fire                Fiery Aegis       1.280576             1.0          1.0             139         5.0
54  Generic Talents                Race / Halfling    Luck of the Little Folk       1.250000             1.0          1.0              16         5.0
55  Generic Talents    Technique / Combat training      Light Armour Training       1.213740             0.0          0.0             131         5.0
56    Class Talents       Corruption / Shadowflame                 Wraithform       1.207143             1.0          1.0             140         5.0
57  Generic Talents            Steamtech / Physics                Electricity       1.176471             1.0          1.0              17         5.0
58    Class Talents     Corruption / Heart of Fire           Devouring Flames       1.121429             1.0          1.0             140         5.0
59  Generic Talents                    Race / Ogre                Ogric Wrath       1.114286             1.0          1.0              35         5.0
60  Generic Talents                   Race / Dwarf  Resilience of the Dwarves       1.000000             1.0          1.0              10         5.0
61  Generic Talents                 Race / Shalore    Secrets of the Eternals       1.000000             1.0          1.0              12         5.0
62    Class Talents       Corruption / Shadowflame                   Darkfire       0.950000             1.0          1.0             140         5.0
63  Generic Talents             Cunning / Survival          Heightened Senses       0.911765             1.0          1.0             136         5.0
64  Generic Talents                   Race / Dwarf              Stone Walking       0.900000             0.5          0.0              10         5.0
65  Generic Talents             Celestial / Chants              Chant Radiant       0.857143             0.0          0.0              14         5.0
66  Generic Talents             Cunning / Survival                      Track       0.842520             1.0          1.0             127         5.0
67    Class Talents       Corruption / Shadowflame                  Fearscape       0.814286             1.0          1.0             140         5.0
68  Generic Talents          Steamtech / Chemistry                  Chemistry       0.764706             1.0          1.0              17         5.0
69  Generic Talents        Corruption / Oppression                  Fearfeast       0.614286             0.0          0.0             140         5.0
70  Generic Talents          Steamtech / Chemistry                 Explosives       0.588235             0.0          0.0              17         5.0
71  Generic Talents        Corruption / Oppression              Mass Hysteria       0.571429             0.5          0.0             140         5.0
72    Class Talents          Corruption / Fearfire            Infernal Breath       0.487603             0.0          0.0             121         5.0
73  Generic Talents    Technique / Combat training             Dagger Mastery       0.464286             0.0          0.0             140         5.0
74    Class Talents     Technique / Combat veteran               Spell Shield       0.378571             0.0          0.0             140         5.0
75  Generic Talents             Cunning / Survival               Danger Sense       0.370079             0.0          0.0             127         5.0
76    Class Talents     Technique / Combat veteran             Quick Recovery       0.364286             0.0          0.0             140         5.0
77  Generic Talents             Corruption / Hexes                Burning Hex       0.321429             0.0          0.0             140         5.0
78    Class Talents     Technique / Combat veteran            Fast Metabolism       0.307143             0.0          0.0             140         5.0
79    Class Talents          Corruption / Fearfire             Maw of Urh'rok       0.225000             0.0          0.0             120         5.0
80  Generic Talents             Corruption / Hexes           Pacification Hex       0.221429             0.0          0.0             140         5.0
81  Generic Talents             Corruption / Hexes             Domination Hex       0.150000             0.0          0.0             140         5.0
82    Class Talents     Technique / Combat veteran            Unending Frenzy       0.135714             0.0          0.0             140         5.0
83  Generic Talents             Corruption / Hexes               Empathic Hex       0.107143             0.0          0.0             140         5.0
84  Generic Talents          Steamtech / Chemistry                Steam Power       0.058824             0.0          0.0              17         5.0
85  Generic Talents            Steamtech / Physics         Compact Steam Tank       0.000000             0.0          0.0              17         5.0